substitutions:
  device_name: "aquaguardian"
  api_url: !secret update_url
  friendly_name: "toaletko"
  
esphome:
  name: ${device_name}
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: "bbt.wc"
    version: "2024.10.3"

esp32:
  board: esp32dev
  framework:
    type: esp-idf

wifi:
  networks:
#  - ssid: !secret wifi_not
#    password: !secret wifi_pass
  - ssid: !secret wifi_iot
    password: !secret wifi_pass      
  # Optional manual IP
  manual_ip:
    static_ip: !secret aquaguardian_ip
    gateway: !secret gateway
    subnet: 255.255.0.0
    dns1: !secret dns1
    dns2: !secret dns2
#  use_address: 172.16.12.71  
  fast_connect: true
  ap:
    ssid: "${friendly_name} Fallback Hotspot"
    password: !secret wifi_pass

captive_portal:

# Enable logging
logger:

api:

dashboard_import:
  package_import_url: !secret package_url
  import_full_config: true # or false

ota:
  - platform: esphome
  - platform: http_request
    #id: ota_flash_action

http_request:
  #verify_ssl: false
  # id: http_client

update:
  - platform: http_request
    name: Firmware Update
    source: ${api_url}

esp32_improv:
  authorizer: none


# web_server:
#   port: 80
#   auth: 
#     username: !secret web_user
#     password: !secret web_pass

mqtt:
  broker: !secret broker_ip
  port: 1883
  username: esphome
  password: !secret mqtt_password
  # ...
  birth_message:
    topic: esphome/${device_name}/status
    payload: online
  will_message:
    topic: esphome/${device_name}/status
    payload: offline


binary_sensor:
  - platform: gpio
    filters:
      - invert
    pin:  GPIO5
    name: light_detector
    device_class: light
#    inverted: true
#    internal: true
#    filters:
#      - invert:
#      - delayed_on: 100ms
#      - delayed_off: 600ms
#      - delayed_on_off: 100ms
#      - autorepeat:
#        - delay: 1s
#          time_off: 100ms
#          time_on: 900ms
#        - delay: 5s
#          time_off: 100ms
#          time_on: 400ms
   
#  - platform: gpio
#    pin: D8
#    name: bad_motion
#    device_class: motion
#    id: motion_sensor

#  - platform: copy
#    source_id: motion_sensor
#    id: zauzece
#    icon: "mdi:heat-pump"
#    name: Occupancy
#    device_class: "occupancy"
#    filters:
#      - invert:
#      - delayed_on: 100ms
#      - delayed_off: 600ms
#      - delayed_on_off: 100ms
#      - autorepeat:
#        - delay: 1s
#          time_off: 100ms
#          time_on: 900ms
#        - delay: 5s
#          time_off: 100ms
#          time_on: 400ms
#      - lambda: |-
#          if (id(motion_sensor).state) {
#            return "OFF";
#           if (id(motion_sensor).state) {
#            return "OFF";
#          } else {
#            return {};
#          }

sensor:
  - platform: dht
    model: DHT22
    pin: GPIO17
    temperature:
#      filters:
#      - offset: -4.0
      name: "${friendly_name} Temperature"
    humidity:
      accuracy_decimals: 1
      name: "${friendly_name} Humidity"
    update_interval: 60s

  - platform: wifi_signal
    name: "${friendly_name} Wifi Signal"
    update_interval: 90s
    
  - platform: uptime
    name: "${friendly_name} UpTime"

switch:
  - platform: output
    name: "Spiegel Licht"
#    icon: "mdi:lamp"
    output: relay


#on_press:
#  then:
#    - light.turn_on:
#        id: some_light_id
#        transition_length: 0.5s
#        red: 0.8
#        green: 1.0
#        blue: !lambda |-
#          // The sensor outputs values from 0 to 100. The blue
#          // part of the light color will be determined by the sensor value.
#          return id(some_sensor).state / 100.0;

button:
  - platform: template
    name: "Update"
    id: firmware_update
    on_press:
      then:
        - ota.http_request.flash:
            md5_url: https://github.com/tominik83/aquaguardian/raw/refs/heads/main/firmware.md5
            url: https://github.com/tominik83/aquaguardian/raw/refs/heads/main/firmware.ota.bin
            username: !secret web_user
            password: !secret web_pass
        - logger.log: "This message should not be displayed because the device reboots"


  
  - platform: shutdown
    name: "Aquaguardian Shutdown"
    entity_category: diagnostic

  - platform: restart
    name: "Aquaguardian Restart"
    entity_category: diagnostic

  - platform: safe_mode
    name: "Aquaguardian Restart (Safe Mode)"
    entity_category: diagnostic
    

light:
  - platform: monochromatic
    name: "TusLED1"
    output: pwm1
    
  - platform: monochromatic
    name: "TusLED2"
    output: pwm2

# Example output entry
output:
  - platform: ledc
    pin: GPIO14
    id: pwm1 

  - platform: ledc
    pin: GPIO15
    id: pwm2

  - platform: gpio
    id: relay
    pin: GPIO16
    
# status_led:
#   pin: D4